### ISSUE TITLE
Callback must be a function

### ISSUE THREAD

**Issue by andreabertagnolli** [f-hj/slsk-client#22]
Got this error on a project that use slsk-client:

> TypeError [ERR_INVALID_CALLBACK]: Callback must be a function  
    at maybeCallback (fs.js:129:9)  
    at Object.writeFile (fs.js:1156:14)  
    at Socket.conn.on (./node_modules/slsk-client/lib/download-peer-file.js:83:10)  
    at Socket.emit (events.js:182:13)  
    at TCP._handle.close (net.js:606:12)  

I think it's just because the function `writeFile` ar row 83 (https://github.com/f-hj/slsk-client/blob/master/lib/download-peer-file.js#L83) is called without a callback

**Comment by fan1200** [comment]
This is also a error that I see regularly when running.

**Comment by andreabertagnolli** [comment]
sould be fixed.
