### ISSUE TITLE
ERR_INDEX_OUT_OF_RANGE

### ISSUE THREAD

**Issue by riteable** [f-hj/slsk-client#5]
Getting the error below sometimes when searching:

```
buffer.js:1015
    throw new errors.RangeError('ERR_INDEX_OUT_OF_RANGE');
    ^

RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1015:11)
    at Buffer.readUInt32LE (buffer.js:1079:5)
    at Message.read32 (/.../slsk-client/lib/message.js:72:25)
    at Message.int32 (/.../slsk-client/lib/message.js:17:50)
    at msgs.forEach.msg (/.../slsk-client/lib/index.js:272:22)
    at Array.forEach (<anonymous>)
    at Messages.forEach (/.../slsk-client/lib/messages.js:41:19)
    at Socket.conn.on.data (/.../slsk-client/lib/index.js:270:10)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
```

**Comment by f-hj** [comment]
Normally this don't happened, added a protection but not sure if this will work correctly

Try with 1.0.8
